// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aoyako/telegram_2ch_res_bot/storage (interfaces: User,Subscription,Info)

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	logic "github.com/aoyako/telegram_2ch_res_bot/logic"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUser is a mock of User interface
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// GetUserByChatID mocks base method
func (m *MockUser) GetUserByChatID(arg0 int64) (*logic.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByChatID", arg0)
	ret0, _ := ret[0].(*logic.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByChatID indicates an expected call of GetUserByChatID
func (mr *MockUserMockRecorder) GetUserByChatID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByChatID", reflect.TypeOf((*MockUser)(nil).GetUserByChatID), arg0)
}

// GetUserByID mocks base method
func (m *MockUser) GetUserByID(arg0 int64) (*logic.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0)
	ret0, _ := ret[0].(*logic.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID
func (mr *MockUserMockRecorder) GetUserByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUser)(nil).GetUserByID), arg0)
}

// GetUsersByPublication mocks base method
func (m *MockUser) GetUsersByPublication(arg0 *logic.Publication) ([]logic.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByPublication", arg0)
	ret0, _ := ret[0].([]logic.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByPublication indicates an expected call of GetUsersByPublication
func (mr *MockUserMockRecorder) GetUsersByPublication(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByPublication", reflect.TypeOf((*MockUser)(nil).GetUsersByPublication), arg0)
}

// IsChatAdmin mocks base method
func (m *MockUser) IsChatAdmin(arg0 int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsChatAdmin", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsChatAdmin indicates an expected call of IsChatAdmin
func (mr *MockUserMockRecorder) IsChatAdmin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsChatAdmin", reflect.TypeOf((*MockUser)(nil).IsChatAdmin), arg0)
}

// IsUserAdmin mocks base method
func (m *MockUser) IsUserAdmin(arg0 *logic.User) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserAdmin", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUserAdmin indicates an expected call of IsUserAdmin
func (mr *MockUserMockRecorder) IsUserAdmin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserAdmin", reflect.TypeOf((*MockUser)(nil).IsUserAdmin), arg0)
}

// Register mocks base method
func (m *MockUser) Register(arg0 *logic.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register
func (mr *MockUserMockRecorder) Register(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUser)(nil).Register), arg0)
}

// Unregister mocks base method
func (m *MockUser) Unregister(arg0 *logic.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unregister", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unregister indicates an expected call of Unregister
func (mr *MockUserMockRecorder) Unregister(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockUser)(nil).Unregister), arg0)
}

// Update mocks base method
func (m *MockUser) Update(arg0 *logic.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockUserMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUser)(nil).Update), arg0)
}

// MockSubscription is a mock of Subscription interface
type MockSubscription struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionMockRecorder
}

// MockSubscriptionMockRecorder is the mock recorder for MockSubscription
type MockSubscriptionMockRecorder struct {
	mock *MockSubscription
}

// NewMockSubscription creates a new mock instance
func NewMockSubscription(ctrl *gomock.Controller) *MockSubscription {
	mock := &MockSubscription{ctrl: ctrl}
	mock.recorder = &MockSubscriptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSubscription) EXPECT() *MockSubscriptionMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockSubscription) Add(arg0 *logic.User, arg1 *logic.Publication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add
func (mr *MockSubscriptionMockRecorder) Add(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockSubscription)(nil).Add), arg0, arg1)
}

// AddDefault mocks base method
func (m *MockSubscription) AddDefault(arg0 *logic.Publication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDefault", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDefault indicates an expected call of AddDefault
func (mr *MockSubscriptionMockRecorder) AddDefault(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDefault", reflect.TypeOf((*MockSubscription)(nil).AddDefault), arg0)
}

// Connect mocks base method
func (m *MockSubscription) Connect(arg0 *logic.User, arg1 *logic.Publication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect
func (mr *MockSubscriptionMockRecorder) Connect(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockSubscription)(nil).Connect), arg0, arg1)
}

// Disonnect mocks base method
func (m *MockSubscription) Disonnect(arg0 *logic.User, arg1 *logic.Publication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disonnect", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disonnect indicates an expected call of Disonnect
func (mr *MockSubscriptionMockRecorder) Disonnect(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disonnect", reflect.TypeOf((*MockSubscription)(nil).Disonnect), arg0, arg1)
}

// GetAllDefaultSubs mocks base method
func (m *MockSubscription) GetAllDefaultSubs() []logic.Publication {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDefaultSubs")
	ret0, _ := ret[0].([]logic.Publication)
	return ret0
}

// GetAllDefaultSubs indicates an expected call of GetAllDefaultSubs
func (mr *MockSubscriptionMockRecorder) GetAllDefaultSubs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDefaultSubs", reflect.TypeOf((*MockSubscription)(nil).GetAllDefaultSubs))
}

// GetAllSubs mocks base method
func (m *MockSubscription) GetAllSubs() []logic.Publication {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubs")
	ret0, _ := ret[0].([]logic.Publication)
	return ret0
}

// GetAllSubs indicates an expected call of GetAllSubs
func (mr *MockSubscriptionMockRecorder) GetAllSubs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubs", reflect.TypeOf((*MockSubscription)(nil).GetAllSubs))
}

// GetSubsByUser mocks base method
func (m *MockSubscription) GetSubsByUser(arg0 *logic.User) ([]logic.Publication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubsByUser", arg0)
	ret0, _ := ret[0].([]logic.Publication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubsByUser indicates an expected call of GetSubsByUser
func (mr *MockSubscriptionMockRecorder) GetSubsByUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubsByUser", reflect.TypeOf((*MockSubscription)(nil).GetSubsByUser), arg0)
}

// Remove mocks base method
func (m *MockSubscription) Remove(arg0 *logic.Publication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove
func (mr *MockSubscriptionMockRecorder) Remove(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockSubscription)(nil).Remove), arg0)
}

// Update mocks base method
func (m *MockSubscription) Update(arg0 *logic.User, arg1 *logic.Publication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockSubscriptionMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubscription)(nil).Update), arg0, arg1)
}

// MockInfo is a mock of Info interface
type MockInfo struct {
	ctrl     *gomock.Controller
	recorder *MockInfoMockRecorder
}

// MockInfoMockRecorder is the mock recorder for MockInfo
type MockInfoMockRecorder struct {
	mock *MockInfo
}

// NewMockInfo creates a new mock instance
func NewMockInfo(ctrl *gomock.Controller) *MockInfo {
	mock := &MockInfo{ctrl: ctrl}
	mock.recorder = &MockInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInfo) EXPECT() *MockInfoMockRecorder {
	return m.recorder
}

// GetLastTimestamp mocks base method
func (m *MockInfo) GetLastTimestamp() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastTimestamp")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetLastTimestamp indicates an expected call of GetLastTimestamp
func (mr *MockInfoMockRecorder) GetLastTimestamp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastTimestamp", reflect.TypeOf((*MockInfo)(nil).GetLastTimestamp))
}

// SetLastTimestamp mocks base method
func (m *MockInfo) SetLastTimestamp(arg0 uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLastTimestamp", arg0)
}

// SetLastTimestamp indicates an expected call of SetLastTimestamp
func (mr *MockInfoMockRecorder) SetLastTimestamp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastTimestamp", reflect.TypeOf((*MockInfo)(nil).SetLastTimestamp), arg0)
}
