db:
  username: "postgres"
  host: "postgres"
  dbname: "postgres"
  sslmode: "disable"

dapi:
  all: "https://2ch.pm/%s/threads.json"
  thread: "https://2ch.pm/%s/res/%s.json"
  resource: "https://2ch.hk%s"

tg:
  admin_id: ["232469683"]

disk:
  path: "src"
  size: 1073714824

polling:
  time: 20