port: "8080"

db:
  username: "postgres"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"

dapi:
  all: "https://2ch.hk/%s/threads.json"
  thread: "https://2ch.hk/%s/res/%s.json"
  resource: "https://2ch.hk%s"

tg:
  admin_id: ["232469683"]