name: test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'

      - name: deps
        run: go get ./...

      - name: build
        run: go build -v cmd/main.go

      - name: test
        run: go test ./...
        
